---
- name: copy the template
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx.conf

- name: create a nginx container
  become: yes
  shell: docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /etc/nginx.conf:/etc/nginx/nginx.conf nginx:1.14
#   docker_container:
#     name: nginx
#     image: nginx:1.14
#     state: started
#     restart_policy: unless-stopped
#     ports:
#      - "80:80"
#      - "443:443"
#     volumes:
#       - /etc/nginx.conf:/etc/nginx/nginx.conf