---
- name: download istio release
  get_url:
    url: "https://github.com/istio/istio/releases/download/{{ istio_version }}/istio-{{ istio_version }}-linux.tar.gz"
    dest: "/tmp/istio-{{ istio_version }}-linux.tar.gz"

- name: unzip istio archive
  unarchive:
    src: "/tmp/istio-{{ istio_version }}-linux.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: cleanup
  file:
    path: "/tmp/istio-{{ istio_version }}-linux.tar.gz"
    state: absent

- name: copy the "istioctl" to the user's binary directory
  copy:
    src: "/tmp/istio-{{ istio_version }}/bin/istioctl"
    dest: /usr/local/bin/istioctl
    remote_src: yes
    mode: +x